### ISSUE TITLE
To-Do: 

### ISSUE THREAD

**Issue by jenniferce** [jenniferce/cheme485_A4#1]
### **Planning report: (2/26)**
- [x] Short abstract (2/22)
- [x] BFD (2/22)
- [x] Reaction Kinetics (2/26)
- [x] Thermodynamics package (2/22)
- [x] Order of magnitude estimate of design costs (2/26) 

### **PFD: (3/4)**
- [x] Pick catalyst 
- [x] Pick temperatures 

### **Final Project (3/9)**
- [x] Letter of transmittal 
- [x] Abstract or executive summary 
- [x] Introduction  
- [x] PFD
- [x] Stream Flow tables
- [x] Manufacturing cost summary 
- [ ] Investment summary  
- [x] Equipment summary     
- [x] Determine the production cost of DME 
- [ ] Incentives to switch from low sulfur diesel to DME
- [ ] Discussion 
- [ ] Conclusion 
- [ ] Recommendations 
- [x] Appendix 
- [x] Equations

**Comment by ccurtis7** [comment]
Great job so far! A note that GitHub's KanBan boards under "Projects" may make it easier to keep track of tasks as they are completed, rather than modifying the markdown in an issue. Check it out if you get the chance.
